# FindFFmpeg.cmake - imported target FFmpeg::FFmpeg. Uses pkg-config when available, otherwise searches
# include/library paths directly (vcpkg, Homebrew without pkg-config, manual SDKs).
find_package(PkgConfig QUIET)
set(_ffm_libs)
set(_ffm_ok TRUE)
foreach(_c IN LISTS FFmpeg_FIND_COMPONENTS)
  set(_found FALSE)
  if(PkgConfig_FOUND)
    pkg_check_modules(PC_${_c} QUIET IMPORTED_TARGET lib${_c})
    if(PC_${_c}_FOUND)
      list(APPEND _ffm_libs PkgConfig::PC_${_c})
      set(_found TRUE)
    endif()
  endif()
  if(NOT _found)
    find_path(FFmpeg_${_c}_INCLUDE_DIR lib${_c}/${_c}.h)
    find_library(FFmpeg_${_c}_LIBRARY NAMES ${_c} lib${_c})
    if(FFmpeg_${_c}_INCLUDE_DIR AND FFmpeg_${_c}_LIBRARY)
      add_library(FFmpeg::${_c} UNKNOWN IMPORTED)
      set_target_properties(FFmpeg::${_c} PROPERTIES IMPORTED_LOCATION "${FFmpeg_${_c}_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${FFmpeg_${_c}_INCLUDE_DIR}")
      list(APPEND _ffm_libs FFmpeg::${_c})
      set(_found TRUE)
    endif()
  endif()
  if(NOT _found)
    set(_ffm_ok FALSE)
    message(STATUS "FFmpeg component lib${_c} not found")
  endif()
endforeach()
if(_ffm_ok AND NOT TARGET FFmpeg::FFmpeg)
  add_library(FFmpeg::FFmpeg INTERFACE IMPORTED)
  target_link_libraries(FFmpeg::FFmpeg INTERFACE ${_ffm_libs})
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFmpeg REQUIRED_VARS _ffm_ok)
